### ISSUE TITLE
Delete system user test case from SL demo

### ISSUE THREAD

**Issue by jason-p-pickering** [pgracio/dhis2-api-system-test#2]
A fuller description is here

https://lists.launchpad.net/dhis2-devs/msg45471.html

which describes deletion of user through the UI. 

The "system" user in the SL demo has a range of objects which are associated with the user. Using the "admin" or other super user, the test should attempt to delete the "system" user from the SL database. Expected result would be successful deletion, but currently, it seems this operation is successful to some extent. The user is deleted, but an HTTP 500 error is returned to the browser, and it appears that in fact the user is not deleted. 

The more generic test would be to add dependent objects which are associated with the "userinfo" object. There are a wide range of them and the deletion handler will need to clean them all up to successfully delete a user.

**Comment by pgracio** [comment]
Duplicated. See https://github.com/dhis2/api-tests/issues/7
